INSERT INTO AUTHORS (NAME) VALUES ('test author 1');
INSERT INTO AUTHORS (NAME) VALUES ('test author 2');
INSERT INTO AUTHORS (NAME) VALUES ('test author 3');
INSERT INTO AUTHORS (NAME) VALUES ('test author 4');

INSERT INTO GENRES (NAME) VALUES ( 'test genre 1' );
INSERT INTO GENRES (NAME) VALUES ( 'test genre 2' );

INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('test title book 1', 1,1);
INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('test title book 2', 2,1);
INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('test title book 3', 2,2);
INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('test title book 4', 3,2);
INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('test title book 5', 4,2);
INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('test title book 6', 3,1);


