INSERT INTO AUTHORS (NAME) VALUES ('Morgan Bruce');
INSERT INTO AUTHORS (NAME) VALUES ('Craig Walls');
INSERT INTO AUTHORS (NAME) VALUES ('Martin Fowler');

INSERT INTO GENRES (NAME) VALUES ( 'Computer science' );

INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('Microservices in Action', 1,1);
INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('Spring in Action, Fifth Edition', 2,1);
INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('Refactoring', 3,1);
INSERT INTO BOOKS (TITLE, AUTHOR_ID, GENRE_ID) VALUES ('Patterns of Enterprise Application Architecture', 3,1);

INSERT INTO COMMENTS (BOOK_ID, TEXT) VALUES ( 1, 'Nice book' );
INSERT INTO COMMENTS (BOOK_ID, TEXT) VALUES ( 1, 'I will try id' );
