DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;

CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR BIGINT,
    GENRE BIGINT);

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR) REFERENCES AUTHORS(ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE) REFERENCES GENRES(ID);